version: '2'
services:
  nginx:
    labels:
      io.rancher.container.hostname_override: container_name
    ports:
      - 80
    tty: true
#    image: nginx
# Argsのテスト
    build:
      context: ./
      args:
        IMAGE_NAME: nginx:1.12.2