version: '2'
catalog:
  name: "nginx"
  version: "v1.0"
  description: "initialize"
  questions:
    - variable: TEST
      label: ABC
      description: |
      type: enum   
      options: *testA
#      options: # List of ptions if using type of `enum`
#        - Option 1
#        - Option 2
services:
  nginx:
    scale: 1

prop:
- &testA
  - Option A
  - Option B